version: '3'

services:
  webserver:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - '443:443'
    networks:
      - totem
    volumes:
      - wordpress_data:/var/www/

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    networks:
      - totem
    volumes:
      - wordpress_data:/var/www/

  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - totem
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

networks:
  totem:
    driver: bridge 
